mvc/viewcomponents/Models/News.cs
namespace Models
{
    public class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
}

mvc/viewcomponents/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

mvc/viewcomponents/Controllers/ViewComponents/NewsViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace ViewComponents
{
    public class NewsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var news = await GetNews();

            return View(news);
        }

        private Task<List<News>> GetNews()
        {
            var news = new List<News>()
            {
                new News() { Id = 1, Title = "News 1"},
                new News() { Id = 2, Title = "News 2"}
            };

            return Task.FromResult(news);
        }
    }
}

mvc/viewcomponents/Views/Home/Index.cshtml
<h1>Hello ASP.NET Core!</h1>

@await Component.InvokeAsync("News")

mvc/viewcomponents/Views/Shared/Components/News/Default.cshtml
@model IEnumerable<Models.News>

<ul>
    @foreach(var news in Model)
    {
        <li><strong>@news.Title</strong></li>
    }
</ul>

mvc/viewcomponents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <div> @RenderBody() </div>
</body>

</html>